### ISSUE TITLE
Could not find a suitable constructor in se.radley.plugin.salat.SalatPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.

### ISSUE THREAD

**Issue by Panshin** [leon/play-salat#66]
- should should be valid *** FAILED ***
 com.google.inject.ConfigurationException: Guice configuration errors:
1) Could not find a suitable constructor in se.radley.plugin.salat.SalatPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
at se.radley.plugin.salat.SalatPlugin.class(SalatPlugin.scala:12)
while locating se.radley.plugin.salat.SalatPlugin

Problem with FakeApplication() in scala test plus :(

**Comment by sevenfrost** [comment]
How did your solve the problem?
